function [] = GUI_2_SAVE(char_img)
% this GUI is for saving the character drawn by the user

    % open a window(figure) for the GUI
    S.fh = figure('units','pixels',...
                'position',[500 300 600 400],...
                'menubar','none',...
                'name','Character Creator',...
                'numbertitle','off',...
                'resize','off',...
                'Color',[0.8588 0.9412 0.8275]);
    % create an axes that will hold the drawn character
    S.ax = axes('units','pix',...
                'position',[100 110 400 180]);
    S.im = char_img;
    % display the drawn character
    imshow(char_img);
    % create a textbox
    S.tb = uicontrol('style','text',...
                'unit','pix',...
                'position',[50 300 500 30],...
                'min',0,'max',2,...
                'fontsize',18,...
                'string','SAVE THIS IMAGE?',...
                'BackgroundColor',[1.0000 0.9490 0.7412],...
                'fontweight', 'bold');
    % create a button for saving the drawing
    S.pb1 = uicontrol('style','push',...
                'units','pix',...
                'position',[100 60 400 40],...
                'fontsize',14,...
                'string',sprintf('Yes'),...
                'backgroundColor',[0.3020 0.4471 0.7412],...
                'foregroundcolor','w',...
                'callback',{@pb1_call,S});
    % create a button for discarding the drawing
    S.pb2 = uicontrol('style','push',...
                'units','pix',...
                'position',[100 10 400 40],...
                'fontsize',14,...
                'string','No',...
                'backgroundColor',[0.3020 0.4471 0.7412],...
                'foregroundcolor','w',...
                'callback',{@pb2_call,S});
end

function [] = pb1_call(varargin)
% button callback function for saving the drawing

    % open a file browser for selecting save location
    [file,path] = uiputfile('*.png');
    
    if file ~= 0
        S = varargin{3};
        % close the current GUI
        close(S.fh);
        % save the drawing
        imwrite(S.im,fullfile(path,file));
        % open a GUI that asks the user if they want to continue
        GUI_3_CONTINUE();
    else
    end
    
end

function [] = pb2_call(varargin)
% callback function of button that discards the drawing

    S = varargin{3};
    % close the current GUI
    close(S.fh);
    % open a GUI that asks the user if they want to continue
    GUI_3_CONTINUE();
end