function [] = GUI_3_CONTINUE()
% this GUI is for confirming if wants to draw another character

    % open a window(figure) for the GUI
    S.fh = figure('units','pixels',...
                'position',[500 300 600 400],...
                'menubar','none',...
                'name','Character Creator',...
                'numbertitle','off',...
                'resize','off',...
                'Color',[0.8588 0.9412 0.8275]);
    % create a textbox
    S.tb = uicontrol('style','text',...
                'unit','pix',...
                'position',[50 300 500 60],...
                'min',0,'max',2,...
                'fontsize',18,...
                'string','DO YOU WANT TO DRAW ANOTHER CHARACTER?',...
                'BackgroundColor',[1.0000 0.9490 0.7412],...
                'fontweight', 'bold');
    % create a button for launching the draw tool
    S.pb1 = uicontrol('style','push',...
                'units','pix',...
                'position',[100 60 400 40],...
                'fontsize',14,...
                'string',sprintf('Yes'),...
                'backgroundColor',[0.3020 0.4471 0.7412],...
                'foregroundcolor','w',...
                'callback',{@pb1_call,S});
    % create a button to quit drawing characters
    S.pb2 = uicontrol('style','push',...
                'units','pix',...
                'position',[100 10 400 40],...
                'fontsize',14,...
                'string','No',...
                'backgroundColor',[0.3020 0.4471 0.7412],...
                'foregroundcolor','w',...
                'callback',{@pb2_call,S});
end

function [] = pb1_call(varargin)
% button callback function for drawing another character

    S = varargin{3};
    % close the current GUI window
    close(S.fh); 
    % start drawing a character
    image = draw_tool();    
    % open the GUI for saving the image
    GUI_2_SAVE(image);
end

function [] = pb2_call(varargin)
% callback function for the button to stop drawing characters

    S = varargin{3};
    % close the current GUI window
    close(S.fh);
end